#!/usr/bin/env bash
set -e pipefail

pushd build
PORT="$(find /dev -name "cu.usb*" |head -n 1)"
if [[ -z ${PORT} ]]; then
  >&2 echo "No serial port found" && exit 1
fi
python $IDF_PATH/tools/idf_monitor.py -p "${PORT}" kbd.elf
popd